#!/usr/bin/env ruby

require 'gtk3'
require 'fileutils'
require 'gstreamer'
require 'glib2'

# Require all ruby files in the application folder recursively
application_root_path = File.expand_path(__dir__)
Dir[File.join(application_root_path,'application/**','*.rb')].each { |file| require file }

# Define the source & target files of the glib-compile-resources command
resource_xml = File.join(application_root_path, 'resources', 'gresources.xml')
resource_bin = File.join(application_root_path, 'gresource.bin')

# Build the binary
system('glib-compile-resources',
       '--target', resource_bin,
       '--sourcedir', File.dirname(resource_xml),
       resource_xml)

Gio::Resources.register Gio::Resource.load(resource_bin)

at_exit do
  # Before exiting, please remove the binary we produced, thanks
  FileUtils.rm_f resource_bin
end


app = Banshy::Application.new
puts app.run
